FROM squidfunk/mkdocs-material

RUN mkdocs -V
RUN pip3 install pymdown-extensions mkdocs-material markdown_blockdiag markdown_include lightgallery meta #--break-system-packages
RUN pip3 install mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin #--break-system-packages